# Generated by Django 4.2.5 on 2023-09-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.CharField(max_length=30),
        ),
    ]
